; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:OKABE_PHONE_PROTO]
platform = espressif32
board = lilygo-t-display
framework = 
	espidf
	arduino
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
	blemasle/MCP23017@^2.0.0
	nhthai173/WebOTA@^1.1.1
board_build.partitions = max_app_4MB.csv
monitor_speed = 115200
upload_speed = 921600
board_build.psram = enable
board_build.filesystem = spiffs
build_type = debug
monitor_filters = 
	esp32_exception_decoder
	colorize
build_flags = 
	-DINV_DISP
	-DDISABLE_ALL_LIBRARY_WARNINGS
	-DCORE_DEBUG_LEVEL=4
	-Wall
	-D OKABE_PHONE_PROTO
	-D BOARD_HAS_PSRAM
	-D USER_SETUP_LOADED=1
	-D ILI9341_DRIVER=1
	-D TFT_MISO=12
	-D TFT_MOSI=23
	-D TFT_SCLK=18
	-D TFT_CS=27
	-D TFT_DC=32
	-D TFT_RST=-1
	-D TFT_BL=4
	-D SPI_FREQUENCY=40000000

[env:OKABE_PHONE_S3_EXP]
platform = espressif32
framework = 
	espidf
	arduino
lib_deps = 
	bodmer/TFT_eSPI
	blemasle/MCP23017@^2.0.0
	nhthai173/WebOTA@^1.1.1
board_build.partitions = 16MB.csv
monitor_speed = 115200
upload_speed = 921600
board_build.psram = enable
board_build.filesystem = spiffs
build_type = debug
monitor_filters = 
	esp32_exception_decoder
	colorize
build_flags = 
	-DDISABLE_ALL_LIBRARY_WARNINGS
	-DCORE_DEBUG_LEVEL=5
	-Wall
	-D OKABE_PHONE_PROTO
	-D BOARD_HAS_PSRAM
	-D USER_SETUP_LOADED=1
	-D ST7789_DRIVER=1
	-D ILI9341_DRIVER
	-D ESP32_S3=1
;	-D INV_DISP
	-D HAS_I2S
	-DI2S_SCK=4
	-DI2S_BCK=5
	-DOP_HAS_BLUETOOTH
	-DOP_HAS_WIFI
	-DI2S_DIN=6
	-DI2S_LRCK=7
	-D SD_CS=-1
	-D SD_SCK=-1
	-D SD_MISO=-1
	-D SD_MOSI=-1
	-D SIM_RX_PIN=35
	-D SIM_TX_PIN=26
	-D I2C_SDA=27
	-D I2C_SCL=28
	-D USE_FSPI_PORT=1
	-D TFT_MOSI=41
	-D TFT_MISO=39
	-D TFT_SCLK=40
	-D TFT_CS=1
	-D TFT_DC=42
	-D TFT_RST=2
	-D TFT_BL=-1
	-D SPI_FREQUENCY=27000000
	-D TFT_WIDTH=240
	-D TFT_HEIGHT=320
	-D TFT_RGB_ORDER=TFT_BGR
board = esp32-s3-devkitc-1
board_upload.flash_size = 16MB
board_build.flash_mode = dio

[env:linux]
platform = native
build_type = debug
build_flags = 
	-DEMU
	-DPC
	-O0
	-g3
	-fsanitize=address
	-fno-omit-frame-pointer
	-Wall
	-Wextra
	-lSDL2
	-lcurl
	-lz
