[esp32_common]
platform = espressif32@6.13.0
framework = espidf
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = spiffs
build_type = debug

monitor_filters =
    esp32_exception_decoder
    colorize

extra_scripts =
    post:scripts/build_recovery.py


[env:OKABE_PHONE_PROTO]
extends = esp32_common

board = lilygo-t-display

board_build.partitions = max_app_4MB.csv
board_build.cmake_extra_args = -DOKABE_BOARD=PROTO

build_flags =
    -DINV_DISP
    -Wall
    -DOKABE_PHONE_PROTO
    -DILI9341_DRIVER=1
    -DTFT_MISO=12
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DTFT_CS=27
    -DTFT_DC=32
    -DTFT_RST=-1
    -DTFT_BL=4
    -DSPI_FREQUENCY=40000000


[env:OKABE_PHONE_S3_EXP]
extends = esp32_common

board = esp32-s3-devkitc-1

board_build.partitions = 16MB.csv
board_build.cmake_extra_args = -DOKABE_BOARD=S3

board_upload.flash_size = 16MB
board_build.flash_mode = dio

build_flags =
    -Wall
    -DST7789_DRIVER=1
    -DESP32_S3=1

    -DHAS_I2S
    -DI2S_SCK=4
    -DI2S_BCK=5
    -DI2S_DIN=6
    -DI2S_LRCK=7

    -DOP_HAS_BLUETOOTH
    -DOP_HAS_WIFI

    -DSD_CS=-1
    -DSD_SCK=-1
    -DSD_MISO=-1
    -DSD_MOSI=-1

    -DSIM_RX_PIN=35
    -DSIM_TX_PIN=26

    -DI2C_SDA=14
    -DI2C_SCL=13

    -DOKABE_MODEM_ENABLED=0

    -DTFT_MOSI=41
    -DTFT_MISO=39
    -DTFT_SCLK=40
    -DTFT_CS=1
    -DTFT_DC=42
    -DTFT_RST=2
    -DTFT_BL=-1
    -DSPI_FREQUENCY=27000000
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
[env:linux]
build_src_filter =
    +<*>
    -<recovery/recovery_main.cpp>
platform = native
build_type = debug
build_flags = 
	-DEMU
	-DPC
	-O0
	-g3
	-fsanitize=address
	-fno-omit-frame-pointer
	-Wall
	-Wextra
	-lSDL2
	-lcurl
	-lz
