; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:OKABE_PHONE_PROTO]
platform = espressif32
board = lilygo-t-display
framework = espidf, arduino
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
	blemasle/MCP23017@^2.0.0
	nhthai173/WebOTA@^1.1.1
board_build.partitions = max_app_4MB.csv
monitor_speed = 115200
upload_speed = 921600
board_build.psram = enable
board_build.filesystem = spiffs
build_type = debug
monitor_filters = esp32_exception_decoder, colorize
build_flags = 
	-DDISABLE_ALL_LIBRARY_WARNINGS
	-DCORE_DEBUG_LEVEL=4
	-Wall
	-D OKABE_PHONE_PROTO
	-D BOARD_HAS_PSRAM
	-D USER_SETUP_LOADED=1
	-D ILI9341_DRIVER=1
	-D TFT_MISO=12
	-D TFT_MOSI=23
	-D TFT_SCLK=18
	-D TFT_CS=27
	-D TFT_DC=32
	-D TFT_RST=-1
	-D TFT_BL=4
	-D SPI_FREQUENCY=40000000


[env:OKABE_PHONE_PROTO_OTA]
platform = espressif32
board = lilygo-t-display
framework = espidf, arduino
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
	blemasle/MCP23017@^2.0.0
	nhthai173/WebOTA@^1.1.1
board_build.partitions = max_app_4MB.csv
monitor_speed = 115200
upload_speed = 921600
board_build.psram = enable
board_build.filesystem = spiffs
build_type = debug
monitor_filters = esp32_exception_decoder, colorize
build_flags = 
	-DDISABLE_ALL_LIBRARY_WARNINGS
	-DCORE_DEBUG_LEVEL=4
	-Wall
	-D OKABE_PHONE_PROTO
	-D BOARD_HAS_PSRAM
	-D USER_SETUP_LOADED=1
	-D ILI9341_DRIVER=1
	-D TFT_MISO=12
	-D TFT_MOSI=23
	-D TFT_SCLK=18
	-D TFT_CS=27
	-D TFT_DC=32
	-D TFT_RST=-1
	-D TFT_BL=4
	-D SPI_FREQUENCY=40000000
upload_protocol = custom
upload_command = curl -F "file=@$SOURCE" http://okabe_phone:80/update


[env:OKABE_PHONE_HW_0]
platform = espressif32
board = lilygo-t-display
framework = espidf, arduino
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
	blemasle/MCP23017@^2.0.0
	nhthai173/WebOTA@^1.1.1
board_build.partitions = max_app_4MB.csv
monitor_speed = 115200
upload_speed = 921600
board_build.psram = enable
board_build.filesystem = spiffs
build_type = debug
monitor_filters = esp32_exception_decoder
build_flags = 
	-DDISABLE_ALL_LIBRARY_WARNINGS
	-D OKABE_PHONE_HW_0
	-DCORE_DEBUG_LEVEL=4
	-DBOARD_HAS_PSRAM
	-D USER_SETUP_LOADED=1
	-D ST7789_DRIVER=1
	-D TFT_MISO=12
	-D TFT_MOSI=23
	-D TFT_SCLK=18
	-D TFT_CS=27
	-D TFT_DC=32
	-D TFT_RST=5
	-D TFT_BL=4
	-D SPI_FREQUENCY=40000000
	-D TFT_RGB_ORDER=TFT_BGR

[env:linux]
platform = native
build_type = debug
build_flags = 
	-DEMU
	-DPC
	-O0
	-g3
	-fno-omit-frame-pointer
	-Wall
	-Wextra
	-lSDL2
lib_deps = 
	bitbank2/PNGdec@^1.1.5
	nhthai173/WebOTA@^1.1.1
