#pragma once
#include <Arduino.h>
#include "../UI/ListMenu.h"
#include "../System/Files.h"
#include "../System/FontManagement.h"
#include "../Input/Input.h"
#include "../Connectivity/_WiFi.h"
#include "../GlobalVariables.h"
#include "../System/Tasks.h"
#include "esp_ota_ops.h"
void e();
void execute_application();