[metadata]
Type=Language
Language=Italian


[translation]
UNKNOWN_STRING="Ошибка" 
; "[Text Error]"
; RECOVERY
; "Seems that you flashed your device wrongly.Refer to the
; instructions for more information."
RECOVERY_FAIL_NO_RES="Sembra che il flash del dispositivo sia stato eseguito incorrettamente. Fare riferimento alle istruzioni per ulteriori informazioni."  
; "There was an error when loading resource file."
RECOVERY_FAIL_FAIL_RES="Si è verificato un errore durante il caricamento del file di risorse."
; "Manually triggered recovery"
RECOVERY_MANUAL="Modalità di ripristino attivata manualmente"   
; "=RECOVERY=\n"
RECOVERY_TITLE="=RIPRISTINO=\n"
; "Choose resource file"
RECOVERY_OPT_CHOOSE_RES="Scegli il file di risorse"   
; "Try again"
RECOVERY_TRY_AGAIN="Riprova"
; "Choose action."
RECOVERY_TITLE_CHOOSE_ACT="Scegli un'azione" 
; RECOVERY END


; BOOT
; "Loading resource file..."
BOOT_LOAD_RES="Caricamento file di risorse..."
; "Initializing SDCard..."
BOOT_INIT_SDCARD="Inizializzando la scheda SD..." 
; "Initializing SPIFFS..."
BOOT_INIT_SPIFFS="Inizializzando SPIFFS..." 
; "Copying file to RAM..."
BOOT_CP_FILE_RAM="Copiando i file nella RAM..." 
; "Initializing RTOS tasks..."
BOOT_INIT_RTOS="Inizializzando processi RTOS..."   

; BOOT END


; RESOURCE SYSTEM
; "Error when reading Main Header"
RES_FAIL_FILE_HEADER="Errore durante la lettura dell'header principale"  
; "Header Mismatch (Wrong file?)"
RES_FAIL_MAGIC_MISMATCH="Header non valido (File sbagliato?)"   
; "File version mismatch."
RES_FAIL_VERSION_MISMATCH="Versione del file non valida." 
; "There is no Images..."
RES_FAIL_NO_IMAGES="non ci sono immagini..."
; "Error reading ImageData"
RES_FAIL_IMGDATA="Errore nella lettura di ImageData"  



; "\nDRAWIMAGE:Imagebuffer Pointer is null\nprobably something wrong
; with SPIRAM/PSRAM"
RES_FAIL_NULL_IMGBUFFER="\nDRAWIMAGE:Puntatore dell'Imagebuffer è nullo\nprobabilmente un problema con SPIRAM/PSRAM"



; "Resource file probably doesn't have\nchecksum!\n\nCRC anchor is
; \"%s\"\nbut expected  \"%s\""
RES_WARN_NO_CHECKSUM="Il file di risorse probabilmente\n non ha un checksum!\n\nIl CRC è \"%s\"\nma dovrebbe essere \"%s\""

; "Checksum check failure:\n\nExpected   0x%08X\nCalculated 0x%08X"
RES_WARN_CHECKSUM_FAILURE="Controllo del checksum non superato:\n\nCorretto:  0x%08X\nCalcolato  0x%08X" 


; RESOURCE SYSTEM END

; "Save Here"
FILEMANAGER_SAVE_HERE="Salva qui"   
; ".."
FILEMANAGER_PREV_FOLDER=".." 


; INFO WINDOW
; "Info"
IW_TITLE_INFO="Informazioni"  
; "ERROR"
IW_TITLE_ERROR="ERRORE" 
; "Task listing is not available."
IW_TASK_LIST_NA="La lista dei processi non è disponibile."
; "Failed to open Image!"
IW_FAIL_OPEN_IMG="Errore nell'apertura dell'immagine!"   
; "Connecting..."
IW_WIFI_CONNECTING="Connessione in corso..." 
; "Not supported..."
IW_NOT_SUPPORTED="Non supportato"   
; "You need to enable wifi first."
IW_WIFI_EN_NEEDED="Devi prima abilitare il Wi-Fi."  
; "Scanning for WiFi Networks..."
IW_WIFI_SCANNING="Scansionando reti Wi-Fi disponibili..."   
; "Wifi is not enabled"
IW_WIFI_ISNT_EN="Wi-Fi attualmente disabilitato"
; "Timeout (idle)"
IW_WIFI_ERR_IDLE="Tempo scaduto"   
; "No SSID avaliable"
IW_WIFI_ERR_NO_SSID="Nessun SSID disponibile"
; "Scan Completed"
IW_WIFI_ERR_SCAN_COMPLETED="Scansione Completata" 
; "Connected!"
IW_WIFI_CONNECTED="Connesso!"  
; "Connection Failed"
IW_WIFI_ERR_CONN_FAIL="Connessione Fallita"  
; "Connection Lost"
IW_WIFI_ERR_CONN_LOST="Connessione Persa"  
; "Disconnected."
IW_WIFI_ERR_DISCONNECTED="Disconnesso."   
; "No WiFi shield"
IW_WIFI_ERR_NO_SHIELD="Non è presente uno shield Wi-Fi"  
; "Unknown Error (%d)."
IW_WIFI_UNKNOWN="Errore sconosciuto (%d)"
; "Loading messages..."
IW_INBOX_LOAD_MSGS="Caricando i messaggi..." 
; "Applying theme..."
IW_APPLYING_THEME="Applicando il tema..."  
; "Failed to open file..."
IW_FILE_OPEN_FAILED="Errore nell'apertura del file..."
; "File downloaded!"
IW_FILE_DOWNLOADED="File scaricato!" 

; INFO WINDOW END

; "< EMPTY >"
LM_EMPTY="< Vuoto >" 

; "Wi-Fi"
LM_WIFI="Wi-Fi"   
; "Wi-Fi Settings"
LM_WIFI_SETTINGS="Impostazioni Wi-Fi"  
; "SSID"
WIFI_SSID="SSID" 
; "Password"
WIFI_PASSWORD="Password" 
; "Connect To Wi-Fi"
WIFI_CONNECT_TITLE="Connettiti al Wi-Fi"
; "Wi-Fi Hotspot"
WIFI_HOTSPOT_TOGGLE="Hotspot Wi-Fi"   
; "Hotspot settings"
WIFI_HOTSPOT_SETTINGS="Impostazioni dell'hotspot" 
; "Scan Wi-Fi networks"
WIFI_SCAN_BUTTON="Trova reti Wi-Fi"  
; "Auto connect"
WIFI_TOGGLE_AUTOCONNECT="Connetti automaticamente"   
; "Auto reconnect"
WIFI_TOGGLE_AUTORECONNECT="Riconnetti automaticamente" 
; "Set hostname"
WIFI_SET_HOSTNAME="Imposta il nome dell'host" 
; "Hostname"
WIFI_HOSTNAME_FIELD="Nome dell'host"   

; "Cancel"
CANCEL_BUTTON="Indietro"   
; "Confirm"
CONFIRM_BUTTON="OK"  
; "Save"
SAVE_BUTTON="Salva" 
; "Connect"
WIFI_CONNECT_BUTTON="Connetti" 

; "Address Book"
LM_ADDRESS_BOOK="Rubrica"  
; "Tasks"
LM_TASKS_RUNNING="Processi" 
; "Task Manager"
LM_TASKS_MANAGER="Gestione Attività" 
; "Enable RAM Monitor"
LM_TASKS_EN_RAM_MON="Abilita Monitor RAM"  
; "Disable RAM Monitor"
LM_TASKS_DIS_RAM_MON="Disabilita Monitor RAM" 

; "Inbox"
MSGS_INBOX="Ricevuti"
; "Outbox"
MSGS_OUTBOX="Inviati"   
   
; "Change Wallpaper"
LM_SET_CHNG_WALLPAPER="Cambia Sfondo" 
; "Set call ringtone"
LM_SET_CALL_RINGTONE="Imposta suoneria chiamate"  
; "Set mail ringtone"
LM_SET_MAIL_RINGTONE="Imposta suoneria messaggi"  
; "Advanced Settings"
LM_SET_ADVANCED_SET="Impostazioni Avanzate"   

; "System Settings"
LM_A_SET_SYSTEM="Sistema"
;"Connectivity"
LM_A_SET_CONNECTIVITY="Connettività"  
; "Look and feel"
LM_A_SET_LOOK_AND_FEEL="Aspetto" 
; "Experimental"
LM_A_SET_EXPERIMENTAL="Esperimenti"  

; "Debug Menu"
LM_EXP_DEBUG_MENU="Debug" 

; "Change Theme"
LM_LAF_CHANGE_THEME="Cambia Tema" 

; "Set Date & Time"
LM_SYS_DATE_TIME="Imposta Data e Ora" 
; "Date"
MENU_DATE="Data"
; "Time"
MENU_TIME="Ora"

; "Input Settings"
LM_SYS_INPUT="Impostazioni input"   
; "Layouts"
LM_INP_LAYOUTS="Layout" 
; "Timings"
LM_INP_TIMINGS="Tempi" 

; "Language"
LM_SYS_LANG = "Lingua"
; "Custom Language"
LM_SYS_LANG_CHOOSE = "Lingua Personalizzata"

; "Confirm Delay: %d ms"
; NOTE: It meant to represent delay from choosing character
; to actually printing it. "Confirm delay" can be confusing
LM_INP_TIME_CONFIRM_DELAY="Durata Selezione Carattere.: %d ms"

; "Recieving call"
TEL_RECIEVING_CALL="Chiamata in entrata" 
; "Calling..."
TEL_CALLING="Chiamando..."
; "End of Call.."
TEL_END_OF_CALL="Fine della chiamata.."

; "Call"
TEL_CONTACTS_OPT_CALL="Chiama" 
; "Outgoing message"
TEL_CONTACTS_OPT_OUTGOING="Invia un messaggio" 
; "Edit"
TEL_CONTACTS_OPT_EDIT="Modifica" 
; "Create"
TEL_CONTACTS_OPT_CREATE="Crea"   
; "Delete"
TEL_CONTACTS_OPT_DELETE="Elimina"   
; "Name"
TEL_CONTACTS_NAME="Nome" 
; "Number"
TEL_CONTACTS_NUMBER="Numero"   
; "Edit Entry"
TEL_CONTACTS_EDIT="Modifica Elemento" 

; "Outgoing Mail"
MSGS_OUTGOING="Messaggi in Uscita"  
; "Continue"
MSGS_OUT_MENU_CONTINUE="Continua" 
; "Send Message"
MSGS_OUT_MENU_SEND="Invia Messaggio" 
; "Delete"
MSGS_OUT_MENU_DELETE="Elimina"   
; Save To Drafts
MSGS_OUT_MENU_SAVE="Salva come Bozza" 

; "Recieve Mail"
MSGS_INCOMING="Messaggi in Entrata"
; "Reply"
MSGS_INC_MENU_REPLY="Rispondi"  
; "Delete"
MSGS_INC_MENU_DELETE="Elimina" 
; "Are you sure about deleting this message?"
MSGS_INC_MENU_DELETE_CONFIRM="Vuoi davvero eliminare questo messaggio?" 

; "Image Viewer"
IMAGE_VIEWER="Visualizzatore di Immagini" 

; "Extra"
LM_EXTRA="Extra"
; "File Browser"
LM_EXTRA_FILE_BROWSER="Esplora File"   
; "View Image"
LM_EXTRA_VIEW_IMAGE="Visualizza Immagine" 
; "Wallpaper Modes"
LM_EXTRA_WALLPAPER_TEST="Modalità Sfondi" 
; "Set Time"
LM_EXTRA_SET_TIME="Imposta l'orario"   
; "Task Manager"
LM_EXTRA_TASK_MANAGER="Gestione Attività"   
; "Package Manager"
LM_EXTRA_PKG_MANAGER="Gestione Pacchetti"

; "Centered"
WALLPAPER_CENTERED="Centra"  
; "Tiled"
WALLPAPER_TILED="Ripeti" 
; "Fill"
WALLPAPER_FILLED="Riempi"
; "Streched"
WALLPAPER_STRETCHED="Allunga" 
; "Fit horizontally"
WALLPAPER_FIT_HOR="Adatta Orizzontalmente"   
; "Fit vertically"
WALLPAPER_FIT_VER="Adatta Verticalmente"   
; "Yes"
CONFIRM_YES="Sì"
; "No"
CONFIRM_NO="No" 
;"Remove package?"
PKGS_CONF_REMOVE="Rimuovere il pacchetto?" 
;"Package removed!"
PKGS_CONF_REMOVED="Pacchetto rimosso!" 
;"Failed to remove the package""
PKGS_ERR_FAIL_REMOVE="Non è stato possibile rimuovere il pacchetto..." 
; "Run package"
; "Запустить пакет! Пусть он летает! хахахахах" Can't translate it in Italian as it wouldn't make sense (T^T)
PKGS_ACT_OPT_RUN="Avvia pacchetto"
 
; "Info"
PKGS_ACT_OPT_INFO="Dettagli" 
; "Remove"
PKGS_ACT_OPT_REMOVE="Rimuovi" 
; "(DEBUG) Unregister"
PKGS_ACT_OPT_UNREGISTER="(DEBUG) Rimuovi dal registro" 

; "Name: %s\nID: %s\nVersion: %s"
PKGS_INFOWINDOW="Nome: %s\nID: %s\nVersione: %s" 

; "Package load error!"
PKGS_LOAD_ERR="Errore durante il caricamento del pacchetto!" 
; "Package loaded!"
PKGS_LOADED="Pacchetto caricato!" 
; "ID already exist.\nPackage not loaded!"
PKGS_ID_EXIST="Esiste già un pacchetto con questo ID. \nPacchetto non caricato!" 

; "Manage packages"
PKGMGR_MANAGE="Gestisci pacchetti" 
; "Add new package"
PKGMGR_ADD="Aggiungi un nuovo pacchetto" 
; "PkgMgr"
PKGMGR="GstPkt" 