[metadata]
Type=Language
Language=Russian


[translation]
UNKNOWN_STRING="Ошибка" 
; "[Text Error]"
; RECOVERY
; "Seems that you flashed your device wrongly.Refer to the
; instructions for more information."
RECOVERY_FAIL_NO_RES="Походу вы не правильно прошили устройство.Посмотрите в документацию для больше информации"  
; "There was an error when loading resource file."
RECOVERY_FAIL_FAIL_RES="Произошла ошибка при загрузке файла ресурсов"
; "Manually triggered recovery"
RECOVERY_MANUAL="Восстановление запущено вручную"   
; "=RECOVERY=\n"
RECOVERY_TITLE="РЭКАВЕРИ"
; "Choose resource file"
RECOVERY_OPT_CHOOSE_RES="Выберите файл ресурсов"   
; "Try again"
RECOVERY_TRY_AGAIN="Попробовать ещё раз"
; "Choose action."
RECOVERY_TITLE_CHOOSE_ACT="Выберите действие" 
; RECOVERY END


; BOOT
; "Loading resource file..."
BOOT_LOAD_RES="Загрузка файла ресурсов..."
; "Initializing SDCard..."
BOOT_INIT_SDCARD="Инициализация карты памяти" 
; "Initializing SPIFFS..."
BOOT_INIT_SPIFFS="Инициализация SPIFFS..." 
; "Copying file to RAM..."
BOOT_CP_FILE_RAM="Копирование файла в ОЗУ..." 
; "Initializing RTOS tasks..."
BOOT_INIT_RTOS="Инициализация ОСРВ..."   

; BOOT END


; RESOURCE SYSTEM
; "Error when reading Main Header"
RES_FAIL_FILE_HEADER="Ошибка при чтении заголовка"  
; "Header Mismatch (Wrong file?)"
RES_FAIL_MAGIC_MISMATCH="Заголовок не совпадает с ожидаемым (Не тот файл?)"   
; "File version mismatch."
RES_FAIL_VERSION_MISMATCH="Версия файла не поддерживается" 
; "There is no Images..."
RES_FAIL_NO_IMAGES="Нету изображений в файле"
; "Error reading ImageData"
RES_FAIL_IMGDATA="Ошибка чтения мета данных"  



; "\nDRAWIMAGE:Imagebuffer Pointer is null\nprobably something wrong
; with SPIRAM/PSRAM"
RES_FAIL_NULL_IMGBUFFER="Указатель на буфер изображений нулевой, возможно что-то не так с внешней ОЗУ"



; "Resource file probably doesn't have\nchecksum!\n\nCRC anchor is
; \"%s\"\nbut expected  \"%s\""
RES_WARN_NO_CHECKSUM="Скорее всего файл ресурсов не имеет \nконтрольной сумы!\n\nЗаголовок контрольной сумы: \"%s\"\nожидалась: \"%s\""

; "Checksum check failure:\n\nExpected   0x%08X\nCalculated 0x%08X"
RES_WARN_CHECKSUM_FAILURE="Ошибка проверки контрольной сумы:\n\nОжидалась   0x%08X\nПосчиталась 0x%08X" 


; RESOURCE SYSTEM END

; "Save Here"
FILEMANAGER_SAVE_HERE="Сохранить здесь"   
; ".."
FILEMANAGER_PREV_FOLDER=".." 


; INFO WINDOW
; "Info"
IW_TITLE_INFO="Информация"  
; "ERROR"
IW_TITLE_ERROR="ОШИБКА" 
; "Task listing is not available."
IW_TASK_LIST_NA="Диспетчер задач не доступен."
; "Failed to open Image!"
IW_FAIL_OPEN_IMG="Ошибка при открытии изображения!"   
; "Connecting..."
IW_WIFI_CONNECTING="Подключение" 
; "Not supported..."
IW_NOT_SUPPORTED="Не поддерживается"   
; "You need to enable wifi first."
IW_WIFI_EN_NEEDED="Вам надо сначала включить Wi-Fi."  
; "Scanning for WiFi Networks..."
IW_WIFI_SCANNING="Сканирование..."   
; "Wifi is not enabled"
IW_WIFI_ISNT_EN="Wi-Fi не включён"
; "Timeout (idle)"
IW_WIFI_ERR_IDLE="Время вышло"   
; "No SSID avaliable"
IW_WIFI_ERR_NO_SSID="SSID не доступен"
; "Scan Completed"
IW_WIFI_ERR_SCAN_COMPLETED="Сканирование завершенно." 
; "Connected!"
IW_WIFI_CONNECTED="Подключено!"  
; "Connection Failed"
IW_WIFI_ERR_CONN_FAIL="Ошибка подключения"  
; "Connection Lost"
IW_WIFI_ERR_CONN_LOST="Подключение потеряно"  
; "Disconnected."
IW_WIFI_ERR_DISCONNECTED="Отключено."   
; "No WiFi shield"
IW_WIFI_ERR_NO_SHIELD="Нету крышки Wi-Fi (Интересно что бы это могло значить?)"  
; "Unknown Error (%d)."
IW_WIFI_UNKNOWN="Неизвестная ошибка (%d)"
; "Loading messages..."
IW_INBOX_LOAD_MSGS="Загрузка сообщений..." 
; "Applying theme..."
IW_APPLYING_THEME="Применение темы..."  
; "Failed to open file..."
IW_FILE_OPEN_FAILED="Произошла ошибка при открытие файла..."
; "File downloaded!"
IW_FILE_DOWNLOADED="Файл скачан!" 

; INFO WINDOW END

; "< EMPTY >"
LM_EMPTY="< Пусто >" 

; "Wi-Fi"
LM_WIFI="Wi-Fi"   
; "Wi-Fi Settings"
LM_WIFI_SETTINGS="Настройки Wi-Fi"  
; "SSID"
WIFI_SSID="Название Сети" 
; "Password"
WIFI_PASSWORD="Пароль" 
; "Connect To Wi-Fi"
WIFI_CONNECT_TITLE="Подключиться к Wi-Fi"
; "Wi-Fi Hotspot"
WIFI_HOTSPOT_TOGGLE="Точка доступа Wi-Fi"   
; "Hotspot settings"
WIFI_HOTSPOT_SETTINGS="Настройка точки доступа" 
; "Scan Wi-Fi networks"
WIFI_SCAN_BUTTON="Сканировать сети Wi-Fi"  
; "Auto connect"
WIFI_TOGGLE_AUTOCONNECT="Автоподключение"   
; "Auto reconnect"
WIFI_TOGGLE_AUTORECONNECT="Авто переподключение" 
; "Set hostname"
WIFI_SET_HOSTNAME="Название хоста" 
; "Hostname"
WIFI_HOSTNAME_FIELD="Название хоста"   

; "Cancel"
CANCEL_BUTTON="Отмена"   
; "Confirm"
CONFIRM_BUTTON="Ок"  
; "Save"
SAVE_BUTTON="Сохр." 
; "Connect"
WIFI_CONNECT_BUTTON="Подкл." 

; "Address Book"
LM_ADDRESS_BOOK="Контакты"  
; "Tasks"
LM_TASKS_RUNNING="Задачи" 
; "Task Manager"
LM_TASKS_MANAGER="Диспетчер задач" 
; "Enable RAM Monitor"
LM_TASKS_EN_RAM_MON="Включить монитор ОЗУ"  
; "Disable RAM Monitor"
LM_TASKS_DIS_RAM_MON="Выключить монитор ОЗУ" 

; "Inbox"
MSGS_INBOX="Входящие"
; "Outbox"
MSGS_OUTBOX="Исходящие"   
   
; "Change Wallpaper"
LM_SET_CHNG_WALLPAPER="Поменять обои" 
; "Set call ringtone"
LM_SET_CALL_RINGTONE="Рингтон дзвонка"  
; "Set mail ringtone"
LM_SET_MAIL_RINGTONE="Рингтон сообщений."  
; "Advanced Settings"
LM_SET_ADVANCED_SET="Расш. настройки"   

; "System Settings"
LM_A_SET_SYSTEM="Система"
;"Connectivity"
LM_A_SET_CONNECTIVITY="Связь"  
; "Look and feel"
LM_A_SET_LOOK_AND_FEEL="Вид" 
; "Experimental"
LM_A_SET_EXPERIMENTAL="Эксперименты"  

; "Debug Menu"
LM_EXP_DEBUG_MENU="Меню отладки." 

; "Change Theme"
LM_LAF_CHANGE_THEME="Поменять тему" 

; "Set Date & Time"
LM_SYS_DATE_TIME="Дата и время" 
; "Date"
MENU_DATE="Дата"
; "Time"
MENU_TIME="Время"

; "Input Settings"
LM_SYS_INPUT="Настройка ввода"   
; "Layouts"
LM_INP_LAYOUTS="Раскладка" 
; "Timings"
LM_INP_TIMINGS="Задержка" 

; "Language"
LM_SYS_LANG = "Язык"
; "Custom Language"
LM_SYS_LANG_CHOOSE = "Свой язык"

; "Confirm Delay: %d ms"
; NOTE: It meant to represent delay from choosing character
; to actually printing it. "Confirm delay" can be confusing
LM_INP_TIME_CONFIRM_DELAY="Заддержка симв.: %d мс"

; "Recieving call"
TEL_RECIEVING_CALL="Входящий звонок" 
; "Calling..."
TEL_CALLING="Дзвоним..."
; "End of Call.."
TEL_END_OF_CALL="Конец дзвонка.."

; "Call"
TEL_CONTACTS_OPT_CALL="Подзвонить" 
; "Outgoing message"
TEL_CONTACTS_OPT_OUTGOING="Выходящее сообщение" 
; "Edit"
TEL_CONTACTS_OPT_EDIT="Редактировать" 
; "Create"
TEL_CONTACTS_OPT_CREATE="Создать"   
; "Delete"
TEL_CONTACTS_OPT_DELETE="Удалить"   
; "Name"
TEL_CONTACTS_NAME="Имя" 
; "Number"
TEL_CONTACTS_NUMBER="Номер телефона"   
; "Edit Entry"
TEL_CONTACTS_EDIT="Редактировать" 

; "Outgoing Mail"
MSGS_OUTGOING="Выходящие сообщения"  
; "Continue"
MSGS_OUT_MENU_CONTINUE="Продолжить" 
; "Send Message"
MSGS_OUT_MENU_SEND="Отправить сообщение" 
; "Delete"
MSGS_OUT_MENU_DELETE="Удалить"   
; Save To Drafts
MSGS_OUT_MENU_SAVE="Сохранить" 

; "Recieve Mail"
MSGS_INCOMING="Получение сообщения"
; "Reply"
MSGS_INC_MENU_REPLY="Ответить"  
; "Delete"
MSGS_INC_MENU_DELETE="Удалить" 
; "Are you sure about deleting this message?"
MSGS_INC_MENU_DELETE_CONFIRM="Вы уверены что хотите удалить данное сообщение?" 

; "Image Viewer"
IMAGE_VIEWER="Просмотр изображений" 

; "Extra"
LM_EXTRA="Дополнительное"
; "File Browser"
LM_EXTRA_FILE_BROWSER="Проводник"   
; "View Image"
LM_EXTRA_VIEW_IMAGE="Посм. Изображение" 
; "Wallpaper Modes"
LM_EXTRA_WALLPAPER_TEST="Режимы обоев" 
; "Set Time"
LM_EXTRA_SET_TIME="Настроить время"   
; "Task Manager"
LM_EXTRA_TASK_MANAGER="Диспетчер задач"   
; "Package Manager"
LM_EXTRA_PKG_MANAGER="Менеджер пакетов"

; "Centered"
WALLPAPER_CENTERED="По середине"  
; "Tiled"
WALLPAPER_TILED="Плиточное" 
; "Fill"
WALLPAPER_FILLED="Заполнить"
; "Streched"
WALLPAPER_STRETCHED="Растянуть" 
; "Fit horizontally"
WALLPAPER_FIT_HOR="Поместить гориз."   
; "Fit vertically"
WALLPAPER_FIT_VER="Поместить верт."   
; "Yes"
CONFIRM_YES="Да"
; "No"
CONFIRM_NO="Нет" 
;"Remove package?"
PKGS_CONF_REMOVE="Удалить пакет?" 
;"Package removed!"
PKGS_CONF_REMOVED="Пакет удалён!" 
;"Failed to remove the package""
PKGS_ERR_FAIL_REMOVE="Не получилось удалить пакет..." 
; "Run package"
; "Запустить пакет! Пусть он летает! хахахахах"
PKGS_ACT_OPT_RUN="Запустить пакет"
 
; "Info"
PKGS_ACT_OPT_INFO="Информация" 
; "Remove"
PKGS_ACT_OPT_REMOVE="Удалить" 
; "(DEBUG) Unregister"
PKGS_ACT_OPT_UNREGISTER="(Отлад.) Разрегистр." 

; "Name: %s\nID: %s\nVersion: %s"
PKGS_INFOWINDOW="Название: %s\nID: %s\nВерсия: %s" 

; "Package load error!"
PKGS_LOAD_ERR="Ошибка загрузки пакета!" 
; "Package loaded!"
PKGS_LOADED="Пакет загружен!" 
; "ID already exist.\nPackage not loaded!"
PKGS_ID_EXIST="Идент. уже существует. \nПакет не загружен!" 

; "Manage packages"
PKGMGR_MANAGE="Управление пакетами" 
; "Add new package"
PKGMGR_ADD="Добавить новый пакет." 
; "PkgMgr"
PKGMGR="Пакетный Менеджер" 