[metadata]
Type=Language
Language=Ukrainian



[translation]
UNKNOWN_STRING="Помилка" 
; "[Text Error]"
; RECOVERY
; "Seems that you flashed your device wrongly.Refer to the
; instructions for more information."
RECOVERY_FAIL_NO_RES="Ви не правильно перепрошили пристрій. Зверніться до інструкції для більшої інформації"  
; "There was an error when loading resource file."
RECOVERY_FAIL_FAIL_RES="Виникла помилка при завантажені файлу ресурсів."
; "Manually triggered recovery"
RECOVERY_MANUAL="Відновлення було відкрито користувачем."   
; "=RECOVERY=\n"
RECOVERY_TITLE="=РЕКАВЕРІ="
; "Choose resource file"
RECOVERY_OPT_CHOOSE_RES="Виберіть файл ресурсів"   
; "Try again"
RECOVERY_TRY_AGAIN="Спробувати ще раз"
; "Choose action."
RECOVERY_TITLE_CHOOSE_ACT="Виберіть дію" 
; RECOVERY END


; BOOT
; "Loading resource file..."
BOOT_LOAD_RES="Завантаження файлу ресурсів..."
; "Initializing SDCard..."
BOOT_INIT_SDCARD="Ініціалізація карти памяті" 
; "Initializing SPIFFS..."
BOOT_INIT_SPIFFS="Ініціалізація SPIFFS..." 
; "Copying file to RAM..."
BOOT_CP_FILE_RAM="Копіювання файлу до ОЗП..." 
; "Initializing RTOS tasks..."
BOOT_INIT_RTOS="Ініціалізація ОСРЧ..."   

; BOOT END


; RESOURCE SYSTEM
; "Error when reading Main Header"
RES_FAIL_FILE_HEADER="Помилка при читанні заголовку"  
; "Header Mismatch (Wrong file?)"
RES_FAIL_MAGIC_MISMATCH="Заголовок не співпадає з очікуваним (Не той файл?)"   
; "File version mismatch."
RES_FAIL_VERSION_MISMATCH="Версія файлу не підтримується" 
; "There is no Images..."
RES_FAIL_NO_IMAGES="Нема зображень в файлі"
; "Error reading ImageData"
RES_FAIL_IMGDATA="Помилка читання мета даних"  



; "\nDRAWIMAGE:Imagebuffer Pointer is null\nprobably something wrong
; with SPIRAM/PSRAM"
RES_FAIL_NULL_IMGBUFFER="Вказівник на буфер зображень нулевий, можливо щось не так з зовнішним ОЗП"



; "Resource file probably doesn't have\nchecksum!\n\nCRC anchor is
; \"%s\"\nbut expected  \"%s\""
RES_WARN_NO_CHECKSUM="Скоріше всього файл ресурсів не має \nконтрольної суми!\n\nЗаголовок контрольної суми: \"%s\"\nочікувалось: \"%s\""

; "Checksum check failure:\n\nExpected   0x%08X\nCalculated 0x%08X"
RES_WARN_CHECKSUM_FAILURE="Помилка перевірки контрольної суми:\n\nОчікувалось   0x%08X\nПорахувалось 0x%08X" 


; RESOURCE SYSTEM END

; "Save Here"
FILEMANAGER_SAVE_HERE="Зберегти тут"  
; ".."
FILEMANAGER_PREV_FOLDER=".." 


; INFO WINDOW
; "Info"
IW_TITLE_INFO="Інфо"  
; "ERROR"
IW_TITLE_ERROR="ПОМИЛКА" 
; "Task listing is not available."
IW_TASK_LIST_NA="Диспетчер завдань не доступний."
; "Failed to open Image!"
IW_FAIL_OPEN_IMG="Помилка при відкриті зображення!"   
; "Connecting..."
IW_WIFI_CONNECTING="Підключення..." 
; "Not supported..."
IW_NOT_SUPPORTED="Не підтримується..."   
; "You need to enable wifi first."
IW_WIFI_EN_NEEDED="Вам треба спочатку ввімкнути Wi-Fi."  
; "Scanning for WiFi Networks..."
IW_WIFI_SCANNING="Сканування..."   
; "Wifi is not enabled"
IW_WIFI_ISNT_EN="Wi-Fi не ввімкнений"
; "Timeout (idle)"
IW_WIFI_ERR_IDLE="Чай вийшов"   
; "No SSID avaliable"
IW_WIFI_ERR_NO_SSID="SSID не доступний"
; "Scan Completed"
IW_WIFI_ERR_SCAN_COMPLETED="Сканування закінчено." 
; "Connected!"
IW_WIFI_CONNECTED="Подключено!"  
; "Connection Failed"
IW_WIFI_ERR_CONN_FAIL="Помилка підключення"  
; "Connection Lost"
IW_WIFI_ERR_CONN_LOST="Підключення загубленно."  
; "Disconnected."
IW_WIFI_ERR_DISCONNECTED="Відключенно."   
; "No WiFi shield"
IW_WIFI_ERR_NO_SHIELD="Немає кришки Wi-Fi (щоб це могло означати?)"  
; "Unknown Error (%d)."
IW_WIFI_UNKNOWN="Невідома помилка (%d)"
; "Loading messages..."
IW_INBOX_LOAD_MSGS="Завантаження повідомлень..." 
; "Applying theme..."
IW_APPLYING_THEME="Застосування теми..."  
; "Failed to open file..."
IW_FILE_OPEN_FAILED="Сталася помилка при відкритті файлу..."
; "File downloaded!"
IW_FILE_DOWNLOADED="Файл завантаженний!" 

; INFO WINDOW END

; "< EMPTY >"
LM_EMPTY="< Пусто >" 

; "Wi-Fi"
LM_WIFI="Wi-Fi"   
; "Wi-Fi Settings"
LM_WIFI_SETTINGS="Налаштування Wi-Fi"  
; "SSID"
WIFI_SSID="Назва мережі" 
; "Password"
WIFI_PASSWORD="Пароль" 
; "Connect To Wi-Fi"
WIFI_CONNECT_TITLE="Підключитись до Wi-Fi"
; "Wi-Fi Hotspot"
WIFI_HOTSPOT_TOGGLE="Точка доступу Wi-Fi"   
; "Hotspot settings"
WIFI_HOTSPOT_SETTINGS="Налаштування точки доступа" 
; "Scan Wi-Fi networks"
WIFI_SCAN_BUTTON="Сканувати Wi-Fi"  
; "Auto connect"
WIFI_TOGGLE_AUTOCONNECT="Автопідключення"   
; "Auto reconnect"
WIFI_TOGGLE_AUTORECONNECT="Авто перепідключення" 
; "Set hostname"
WIFI_SET_HOSTNAME="Поставити назву хоста" 
; "Hostname"
WIFI_HOSTNAME_FIELD="Назва хоста"   

; "Cancel"
CANCEL_BUTTON="Відміна"   
; "Confirm"
CONFIRM_BUTTON="Ок"  
; "Save"
SAVE_BUTTON="Збер." 
; "Connect"
WIFI_CONNECT_BUTTON="Підкл." 

; "Address Book"
LM_ADDRESS_BOOK="Контакти"  
; "Tasks"
LM_TASKS_RUNNING="Задачі" 
; "Task Manager"
LM_TASKS_MANAGER="Диспечер задач" 
; "Enable RAM Monitor"
LM_TASKS_EN_RAM_MON="Включити монітор ОЗУ"  
; "Disable RAM Monitor"
LM_TASKS_DIS_RAM_MON="Виключити монітор ОЗУ" 

; "Inbox"
MSGS_INBOX="Вхідні"
; "Outbox"
MSGS_OUTBOX="Вихідні"   
   
; "Change Wallpaper"
LM_SET_CHNG_WALLPAPER="Змінити шпалери" 
; "Set call ringtone"
LM_SET_CALL_RINGTONE="Рингтон дзвінка"  
; "Set mail ringtone"
LM_SET_MAIL_RINGTONE="Рингтон повідомлень"  
; "Advanced Settings"
LM_SET_ADVANCED_SET="Розш. налаштування"   

; "System Settings"
LM_A_SET_SYSTEM="Система"
;"Connectivity"
LM_A_SET_CONNECTIVITY="Связок"  
; "Look and feel"
LM_A_SET_LOOK_AND_FEEL="Вигляд" 
; "Experimental"
LM_A_SET_EXPERIMENTAL="Експерименти"  

; "Debug Menu"
LM_EXP_DEBUG_MENU="Меню отладки" 

; "Change Theme"
LM_LAF_CHANGE_THEME="Змінити тему" 

; "Set Date & Time"
LM_SYS_DATE_TIME="Дата і час" 
; "Date"
MENU_DATE="Дата"
; "Time"
MENU_TIME="Час"

; "Input Settings"
LM_SYS_INPUT="Налаштування вводу"   
; "Layouts"
LM_INP_LAYOUTS="Розкладка" 
; "Timings"
LM_INP_TIMINGS="Затримка" 


; "Language"
LM_SYS_LANG = "Мова"
; "Custom Language"
LM_SYS_LANG_CHOOSE = "Своя мова"

; "Confirm Delay: %d ms"
; NOTE: It meant to represent delay from choosing character
; to actually printing it. "Confirm delay" can be confusing
LM_INP_TIME_CONFIRM_DELAY="Затримка симв.: %d мс"

; "Recieving call"
TEL_RECIEVING_CALL="Входящий дзвінок" 
; "Calling..."
TEL_CALLING="Дзвонимо..."
; "End of Call.."
TEL_END_OF_CALL="Кінец дзвінка.."

; "Call"
TEL_CONTACTS_OPT_CALL="Подзвонити" 
; "Outgoing message"
TEL_CONTACTS_OPT_OUTGOING="Вихідне повідомлення" 
; "Edit"
TEL_CONTACTS_OPT_EDIT="Редагувати" 
; "Create"
TEL_CONTACTS_OPT_CREATE="Створити"   
; "Delete"
TEL_CONTACTS_OPT_DELETE="Видалити"   
; "Name"
TEL_CONTACTS_NAME="Ім'я" 
; "Number"
TEL_CONTACTS_NUMBER="Номер телефону"   
; "Edit Entry"
TEL_CONTACTS_EDIT="Редагувати" 

; "Outgoing Mail"
MSGS_OUTGOING="Вихідні повідомлення"  
; "Continue"
MSGS_OUT_MENU_CONTINUE="Продовжити" 
; "Send Message"
MSGS_OUT_MENU_SEND="Відправити повідомлення" 
; "Delete"
MSGS_OUT_MENU_DELETE="Видалити"   
; Save To Drafts
MSGS_OUT_MENU_SAVE="Зберігти" 

; "Recieve Mail"
MSGS_INCOMING="Отримання повідомлення"
; "Reply"
MSGS_INC_MENU_REPLY="Відповісти"  
; "Delete"
MSGS_INC_MENU_DELETE="Видалити" 
; "Are you sure about deleting this message?"
MSGS_INC_MENU_DELETE_CONFIRM="Ви впевнені що хочете видалити це повідомлення?" 

; "Image Viewer"
IMAGE_VIEWER="Перегляд зображень" 

; "Extra"
LM_EXTRA="Додатково"
; "File Browser"
LM_EXTRA_FILE_BROWSER="Файли"   
; "View Image"
LM_EXTRA_VIEW_IMAGE="Подив. Зображення" 
; "Wallpaper Modes"
LM_EXTRA_WALLPAPER_TEST="Режими шпалерів" 
; "Set Time"
LM_EXTRA_SET_TIME="Налаштування часу"   
; "Task Manager"
LM_EXTRA_TASK_MANAGER="Диспетчер завдань"   
; "Package Manager"
LM_EXTRA_PKG_MANAGER="Менеджер пакетів"

; "Centered"
WALLPAPER_CENTERED="По середині"  
; "Tiled"
WALLPAPER_TILED="Плитчне" 
; "Fill"
WALLPAPER_FILLED="Заповнить"
; "Streched"
WALLPAPER_STRETCHED="Розтягнути" 
; "Fit horizontally"
WALLPAPER_FIT_HOR="Поместити гориз."   
; "Fit vertically"
WALLPAPER_FIT_VER="Поместити верт."   
; "Yes"
CONFIRM_YES="Так"
; "No"
CONFIRM_NO="Ні" 
;"Remove package?"
PKGS_CONF_REMOVE="Видалити пакет?" 
;"Package removed!"
PKGS_CONF_REMOVED="Пакет Видалений!" 
;"Failed to remove the package""
PKGS_ERR_FAIL_REMOVE="Не получилось видалити пакет..." 
; "Run package"
; "Запустити пакет! Хай він летає! хахахахах"
PKGS_ACT_OPT_RUN="Запустити пакет"
 
; "Info"
PKGS_ACT_OPT_INFO="Інформація" 
; "Remove"
PKGS_ACT_OPT_REMOVE="Видалити" 
; "(DEBUG) Unregister"
PKGS_ACT_OPT_UNREGISTER="(Відлад.) Розреєстр." 

; "Name: %s\nID: %s\nVersion: %s"
PKGS_INFOWINDOW="Назва: %s\nID: %s\nВерсія: %s" 

; "Package load error!"
PKGS_LOAD_ERR="Помилка завантаження пакету!" 
; "Package loaded!"
PKGS_LOADED="Пакет завантаженний!" 
; "ID already exist.\nPackage not loaded!"
PKGS_ID_EXIST="Ідент. вже існує. \nПакет не завантажений!" 

; "Manage packages"
PKGMGR_MANAGE="Управління пакетами" 
; "Add new package"
PKGMGR_ADD="Добавити новий пакет." 
; "PkgMgr"
PKGMGR="Пакетний Менеджер" 